### ISSUE TITLE
all wrong

### ISSUE THREAD

**Issue by worldofnick** [TarunSunkaraneni/LloydAlgorithm#1]
sorry Tarun this code is all wrong plz disable GitHub profile and transfer to byu. thanks - nick

**Comment by TarunSunkaraneni** [comment]
Dear Nick, 
Thanks for your input. After serious consideration of your comment, accounting of both my code and my college education, i have decided to not follow your suggestion. If you can replicate the problem and send our support team a screenshot or steps to reproduce the issue and we will get back to you within the next 5 business days to follow up with your query. 
Thanks for everything - tarun

**Comment by worldofnick** [comment]
to replicate bug plz navigate to `https://cis.utah.edu/`, login, then navigate to the `registration` tab and proceeded to click `Drop Out`

thanks - nicholas r porter
